services:
  - type: web
    name: covidash-tracker
    env: python
    plan: free
    region: oregon  # or virginia, singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: UPDATE_INTERVAL_HOURS
        value: "24"
      - key: DISEASE_SH_API
        value: "https://disease.sh/v3/covid-19"
      - key: CDC_API_BASE
        value: "https://data.cdc.gov/resource"
      - key: PORT
        value: "10000"
    healthCheckPath: "/api/health"
